Feature event registration
celements/celements-course pull request #2
Opened 2016-10-04 15:45 UTC by ebeutler

First, basic, implementation for event attendance registration

2016-10-04 16:49 UTC, fpichler requested changes
same small changes

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/CourseScriptService.java
>    DocumentReference getDocRefForFullName(String courseFN) {
Please mark getDocRefForFullName as deprecated with hint to org.xwiki.model.internal.scripting.ModelScriptService

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/CourseScriptService.java
> +      XWikiDocument courseDoc = getContext().getWiki().getDocument(getDocRefForFullName(courseFN),
please change to use modelAccess. getDocument with changing the document is potentially spoiling the document cache.

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/registration/Person.java
> +public class Person {
please add annotation @NotThreadSafe

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/registration/RegistrationData.java
> +public class RegistrationData {
please add annotation @NotThreadSafe

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    XWikiDocument courseDoc = getContext().getWiki().getDocument(courseDocRef, getContext());
please refactor the two lines 77,78 to one modelAccess.getXObject(docRef, classRef)

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    XWikiDocument typeDoc = getContext().getWiki().getDocument(courseTypeDocRef, getContext());
please refactor the two lines 92, 93 to one modelAccess.getXObject(docRef, classRef). It ensures that not XWikiDocument is accessible and hence is may not be stored (after readonly get).

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    // (event_reg_verification_mail_subject)
please add Jira Issue with TODO and mention issue number in TODO comment

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    String clientInfo = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
Please use StringBuilder

2016-10-04 16:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    return new SpaceReference(eventid.replaceAll("\\.", "_").replaceAll(":", "_"),
please change to one replaceAll with combined regex [:.]

2016-10-04 16:49 UTC, fpichler commented on src/test/java/com/celements/course/CourseScriptServiceTest.java
>      xwiki = createMock(XWiki.class);
please replace line 54,55 with getWikiMock()

2016-10-04 16:49 UTC, fpichler commented on src/test/java/com/celements/course/service/CourseServiceTest.java
> +  public void setUp_CourseServiceTest() throws Exception {
please rename to "prepareTest" instead of setUp_<classname>

2016-10-05 12:54 UTC, ebeutler commented on src/main/java/com/celements/course/CourseScriptService.java
>    DocumentReference getDocRefForFullName(String courseFN) {
Replaced it instead of deprecating, since it's not a public method

2016-10-05 13:40 UTC, ebeutler commented on src/main/java/com/celements/course/service/CourseService.java
> +    // (event_reg_verification_mail_subject)
https://synjira.atlassian.net/browse/CELDEV-357

2016-10-05 14:05 UTC, ebeutler commented
Requested changes made

2016-10-06 08:49 UTC, fpichler requested changes
some minor things.

2016-10-06 08:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
>      if (courseObj != null) {
please move into try block.

2016-10-06 08:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
>      if (typeObj != null) {
please move into try block.

2016-10-06 08:49 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    // TODO https://synjira.atlassian.net/browse/CELDEV-357 (Event Registration
only CELDEV-357 is needed. URL might change.

2016-10-12 16:13 UTC, merged