New is confirmed
celements/celements-course pull request #5
Opened 2017-03-10 15:15 UTC by dkhasham

related Ticket: https://synjira.atlassian.net/browse/PROGON-404

2017-03-12 15:00 UTC, fpichler requested changes

2017-03-12 15:00 UTC, fpichler commented on src/main/java/com/celements/course/CourseScriptService.java
> +  public CourseConfirmState getConfirmeState(DocumentReference objDocRef) {
- please choose better naming e.g. orderDocRef, registrationDocRef or regDocRef
- add @Null or @NotNull to all parameter and return values in public methods

2017-03-12 15:00 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseConfirmState.java
> +  CONFIRMED("confirmed"),
you do not need an aditional String property holding the name of the enum

2017-03-12 15:00 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +        String state = obj.getStringValue("status");
please use use `CourseConfirmState.valueOf(Strings.nullToEmpty(obj.getStringValue("status")))` to convert to a CourseConfirmState

2017-03-12 15:00 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +        if ((state.equals(CourseConfirmState.CONFIRMED.id) && (index == 0)) || (state.equals(
after changing `state` to a `CourseConfirmState` you may compare directly with == and !=

2017-03-12 15:00 UTC, fpichler commented on src/main/java/com/celements/course/service/ICourseServiceRole.java
> +  public CourseConfirmState getConfirmeState(DocumentReference objDocRef);
-  please choose better naming e.g. orderDocRef, registrationDocRef or regDocRef
-  add @Null or @NotNull to all parameter and return values in public methods at least in the interfaces/ComponentRoles

2017-03-12 15:00 UTC, fpichler commented on src/test/java/com/celements/course/service/CourseServiceTestModelAccessMock.java
> +public class CourseServiceTestModelAccessMock extends AbstractComponentTest {
names of junit test classes MUST end on *Test. Otherwise they are not executed in maven context!

2017-03-15 08:52 UTC, fpichler requested changes

2017-03-15 08:52 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +  public CourseConfirmState getConfirmeState(DocumentReference regDocRef) {
spelling.

2017-03-15 08:52 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseConfirmState.java
> +      return Optional.fromNullable(CourseConfirmState.valueOf(name.toUpperCase()));
valueOf never returns null. Therefore use Optional.of() instead

2017-03-15 08:52 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseConfirmState.java
> +  public static Optional<CourseConfirmState> convertStringToEnum(String name) {
add `NotNull` annotation to name parameter and return value

2017-03-15 08:52 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +    if ((state.equals(CourseConfirmState.CONFIRMED) && (index == 0)) || (state.equals(
do not use .equals( to compare enums

2017-03-15 08:52 UTC, fpichler commented on src/main/java/com/celements/course/service/CourseService.java
> +          if (isConfirmed(state.get(), confirmState, index)) {
I suggest to use a switch statement. Initialize confirmState with null. use following transition rules:
null -> state.get()
UNCONFIRMED, CONFIRMED if (state.get() != confirmState) -> PARTIALCONFIRMED
default -> nothing changes
if (confirmState == null) return UNCONFIRMED else return confirmState

2017-03-15 11:29 UTC, msladek requested changes

2017-03-15 11:29 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +        modelContext.getXWikiContext().getDatabase());
getXWikiContext is discouraged, see javadoc

2017-03-15 11:29 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +      List<BaseObject> partiObjs = modelAccess.getXObjects(regDocRef, courseParticipantClassRef);
please inline

2017-03-15 11:29 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +          switch (confirmState) {
confirmState always is UNDEFINED at this point (init value)

2017-03-15 11:29 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +      List<BaseObject> partiObjs = modelAccess.getXObjects(regDocRef, courseParticipantClassRef);
also, leads to NPE if regDocRef is null, yet this is possible according to current contract. change to NotNull

2017-03-15 11:29 UTC, msladek commented on src/main/java/com/celements/course/CourseScriptService.java
> +    return null;
or return UNDEFINED?

2017-03-15 12:56 UTC, dkhasham commented on src/main/java/com/celements/course/service/CourseService.java
> +          switch (confirmState) {
the confirmState isn't always UNDEFINED at this point. see for loop.

2017-03-15 13:43 UTC, fpichler approved these changes

2017-03-15 15:15 UTC, msladek requested changes

2017-03-15 15:15 UTC, msladek commented on src/main/java/com/celements/course/CourseScriptService.java
> +          .getCourseTypeForCourse(docRef)).or(docRef);
our formatter doesn't break like that, what happened here?

2017-03-15 15:15 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +          .getName()));
our formatter doesn't break like that, what happened here?

2017-03-16 16:58 UTC, msladek requested changes

2017-03-16 16:58 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +          switch (confirmState) {
i think the switch and break statements make this part hard to understand. wouldn't this be much easier:
```java
if (confirmState == CourseConfirmState.UNDEFINED) {
  confirmState = state.get();
} else if (confirmState != state.get()) {
  confirmState = CourseConfirmState.PARTIALCONFIRMED;
  break;
}
```

2017-03-16 17:00 UTC, msladek approved these changes

2017-03-16 17:01 UTC, merged