get a map of annanoucements and recent numbers for course
celements/celements-course pull request #7
Opened 2017-05-15 12:30 UTC by dkhasham

related Ticket: https://synjira.atlassian.net/browse/PROGON-494

2017-05-15 14:02 UTC, ebeutler approved these changes

2017-05-15 14:12 UTC, msladek commented
please let me review these changes too

2017-05-15 14:30 UTC, msladek requested changes
Issue requirement is not met, please add the following methods to the CourseService
```
public long getAnnouncementCount(@NotNull SpaceReference regSpaceRef)
public long getAnnouncementCount(@NotNull SpaceReference regSpaceRef, @Nullable CourseConfirmState state)
```
they make use of  `getAnnouncementsForCourse(...)`. The ScriptService can still compile a map using the 3 methods from the CourseService

2017-05-15 14:30 UTC, msladek commented on src/main/java/com/celements/course/service/ICourseServiceRole.java
> +      DocumentReference partiClassRef);
- NotNull/Nullable missing on parameters
- return `List<DocumentReference>`, the elements are always documents
- I don't think `partiClassRef` should be part of signature
- add `List<String> sortFields` to signature, makes it more reusable

2017-05-15 14:30 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +      retVal = result.getResults();
directly `return result.getResults(DocumentReference.class)`

2017-05-15 14:30 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +    } catch (LuceneSearchException exp) {
don't catch LuceneSearchException, instead the method should throw it

2017-05-17 10:36 UTC, msladek requested changes

2017-05-17 10:36 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +
empty line

2017-05-17 10:36 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +    for (EntityReference announcement : announcementList) {
use consistent naming, either announcement or registration

2017-05-17 10:36 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +      DocumentReference announcementDocRef = new DocumentReference(announcement);
announcement is already DocumentReference

2017-05-17 10:36 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +    return getRegistrationsForCourse(getRegistrationSpace(courseDocRef), sortFields);
use sortFields null instead of empty list

2017-05-17 10:36 UTC, msladek commented on src/main/java/com/celements/course/service/CourseService.java
> +          if (state == null) {
if `state == null` there is no need to loop the objects, instead `retVal += partiObjs.size()`

2017-05-17 10:37 UTC, msladek commented
that was more the idea, thanks. some small changes

2017-05-17 19:37 UTC, msladek approved these changes

2017-05-23 08:27 UTC, merged